# Generated by Django 3.2.16 on 2023-01-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230103_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cardImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
