# Generated by Django 3.2.16 on 2023-01-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230103_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cardImage',
            field=models.URLField(),
        ),
    ]
