# Generated by Django 3.2.16 on 2023-01-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_products_cardimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='cardImage',
            new_name='cardLink',
        ),
    ]
