# Generated by Django 3.2.16 on 2023-01-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_cardimage_products_cardlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cardLink',
            field=models.URLField(max_length=500),
        ),
    ]
