# Generated by Django 3.2.16 on 2023-01-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_products_cardlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image1',
            field=models.ImageField(blank=True, default='post_images/default.jpg', null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.ImageField(blank=True, default='post_images/default.jpg', null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.ImageField(blank=True, default='post_images/default.jpg', null=True, upload_to='post_images/'),
        ),
    ]
