# Generated by Django 3.2.16 on 2023-01-14 19:47

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20230103_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
